-- GOR-86: Lark Docs & Wiki Integration
INSERT INTO tools (name, description, schema, handler, enabled) VALUES
('lark_docs_read', 'Read Lark document content by document_id. Returns the full text content of a Lark docx document.', '{"type":"object","properties":{"documentId":{"type":"string","description":"The Lark document ID (from URL or API)"},"appId":{"type":"string","description":"Lark app ID (optional, uses default if not set)"}},"required":["documentId"]}', 'lark_docs_read', true),
('lark_docs_create', 'Create a new Lark document with a title. Optionally specify a folder token.', '{"type":"object","properties":{"title":{"type":"string","description":"Document title"},"folderToken":{"type":"string","description":"Optional folder to create the document in"},"appId":{"type":"string","description":"Lark app ID (optional)"}},"required":["title"]}', 'lark_docs_create', true),
('lark_docs_update', 'Add content (text block) to an existing Lark document.', '{"type":"object","properties":{"documentId":{"type":"string","description":"The Lark document ID"},"content":{"type":"string","description":"Text content to add to the document"},"blockId":{"type":"string","description":"Optional block ID to append to (defaults to document root)"},"appId":{"type":"string","description":"Lark app ID (optional)"}},"required":["documentId","content"]}', 'lark_docs_update', true),
('lark_wiki_list_spaces', 'List all Lark wiki spaces accessible to the user.', '{"type":"object","properties":{"appId":{"type":"string","description":"Lark app ID (optional)"}}}', 'lark_wiki_list_spaces', true),
('lark_wiki_list_nodes', 'List documents/nodes in a Lark wiki space. Optionally filter by parent node.', '{"type":"object","properties":{"spaceId":{"type":"string","description":"Wiki space ID"},"parentNodeToken":{"type":"string","description":"Optional parent node token to list children"},"appId":{"type":"string","description":"Lark app ID (optional)"}},"required":["spaceId"]}', 'lark_wiki_list_nodes', true),
('lark_wiki_get_node', 'Get details of a Lark wiki node by its token.', '{"type":"object","properties":{"token":{"type":"string","description":"Node token"},"appId":{"type":"string","description":"Lark app ID (optional)"}},"required":["token"]}', 'lark_wiki_get_node', true)
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description, schema = EXCLUDED.schema, enabled = EXCLUDED.enabled;
